- name: Create a directory for the postgres-operator
  file: 
    state: directory
    name: "{{POSTGRES_OPERATOR_SRC}}"
    owner: "{{USER_NAME}}"
  become: true
- name: Clone the postgres-operator git repository. 
  git: 
    repo: "{{POSTGRES_OPERATOR_REPO}}"
    dest: "{{POSTGRES_OPERATOR_SRC}}"
    version: "{{POSTGRES_OPERATOR_TAG}}"
- name: Setup pgo-metrics ansible role in ~/.ansible/roles/
  file: 
    src: "{{POSTGRES_OPERATOR_SRC}}/ansible/roles/pgo-metrics"
    dest: "~/.ansible/roles/pgo-metrics"
    state: link
- name: Setup pgo-operator ansible role in ~/.ansible/roles/
  file: 
    src: "{{POSTGRES_OPERATOR_SRC}}/ansible/roles/pgo-operator"
    dest: "~/.ansible/roles/pgo-operator"
    state: link
- name: Setup pgo-preflight ansible role in ~/.ansible/roles/
  file: 
    src: "{{POSTGRES_OPERATOR_SRC}}/ansible/roles/pgo-preflight"
    dest: "~/.ansible/roles/pgo-preflight"
    state: link

