- name: "Create the project file directory {{ FILE.path | dirname }}"
  file:
    state: directory
    path: "{{ FILE.path | dirname }}"
- name: "Check for the project file {{ FILE.template }}"
  stat: 
    path: "{{ FILE.path }}"
  register: FILE_EXISTS
- name: "Create the project file {{ FILE.template }}"
  copy:
    content: "{{ lookup('template', FILE.template) | replace('\\{\\{','{{') | replace('\\}\\}', '}}') }}"
    dest: "{{ FILE.path }}"
  when: (FILE.once is not defined or FILE.once == false) or FILE_EXISTS.stat.exists == false
