---
- name: Install computate-medicale image stream on OpenShift
  k8s: 
    state: present
    name: computate-medicale
    host: "{{COMPUTATE_MEDICALE_HOST}}"
    api_key: "{{COMPUTATE_MEDICALE_TOKEN}}"
    namespace: "{{COMPUTATE_MEDICALE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_medicale_image_stream.yml.j2') }}"
- name: Install computate-medicale secret on OpenShift
  k8s: 
    state: present
    name: computate-medicale-secret
    host: "{{COMPUTATE_MEDICALE_HOST}}"
    api_key: "{{COMPUTATE_MEDICALE_TOKEN}}"
    namespace: "{{COMPUTATE_MEDICALE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_medicale_secret.j2') }}"
- name: Install computate-medicale keystore secrets on OpenShift
  k8s: 
    state: present
    name: computate-medicale-keystore
    host: "{{COMPUTATE_MEDICALE_HOST}}"
    api_key: "{{COMPUTATE_MEDICALE_TOKEN}}"
    namespace: "{{COMPUTATE_MEDICALE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_medicale_keystore.j2') }}"
- name: Install computate-medicale build config on OpenShift
  k8s: 
    state: present
    name: computate-medicale
    host: "{{COMPUTATE_MEDICALE_HOST}}"
    api_key: "{{COMPUTATE_MEDICALE_TOKEN}}"
    namespace: "{{COMPUTATE_MEDICALE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_medicale_build_config.yml.j2') }}"
- name: Install computate-medicale deployment config on OpenShift
  k8s: 
    state: present
    name: computate-medicale
    host: "{{COMPUTATE_MEDICALE_HOST}}"
    api_key: "{{COMPUTATE_MEDICALE_TOKEN}}"
    namespace: "{{COMPUTATE_MEDICALE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_medicale_deployment_config.yml.j2') }}"
- name: Install computate-medicale service on OpenShift
  k8s: 
    state: present
    name: computate-medicale
    host: "{{COMPUTATE_MEDICALE_HOST}}"
    api_key: "{{COMPUTATE_MEDICALE_TOKEN}}"
    namespace: "{{COMPUTATE_MEDICALE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_medicale_service.yml.j2') }}"
- name: Install computate-medicale route on OpenShift
  k8s: 
    state: present
    name: computate-medicale
    host: "{{COMPUTATE_MEDICALE_HOST}}"
    api_key: "{{COMPUTATE_MEDICALE_TOKEN}}"
    namespace: "{{COMPUTATE_MEDICALE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_medicale_route.yml.j2') }}"
- name: Create Solr collection
  shell: "oc login {{COMPUTATE_MEDICALE_HOST}} --token={{REDHAT_OPENSHIFT_TOKEN}} && oc exec $(oc get pod -l app=computate-solr -o jsonpath='{.items[0].metadata.name}') -n medical -- /opt/solr/bin/solr create_collection -c site -n computate || true"
  register: create_collection
- name: Print create_collection command
  debug:
    var: create_collection
