
####################
# Certbot defaults #
####################

COMPUTATE_CERTBOT_DOMAIN_NAME: "..."

#####################################
# project system defaults #
#####################################

# The name of this application. 
PROJECT_NAME: project
# The default source code directory for the computate application which helps generate and translate most the code. 
COMPUTATE_SRC: "/usr/local/src/computate"
# The default source code directory for the project project. 
PROJECT_SRC: "/usr/local/src/{{PROJECT_NAME}}"
# The default language of the project project code which is US English. 
PROJECT_LANG: "enUS"
# The default config file for the project project. 
PROJECT_CONFIG: "{{PROJECT_SRC}}/config/{{PROJECT_NAME}}.config"
# The US English config file for the project project. 
PROJECT_CONFIG_enUS: "{{PROJECT_SRC}}/config/{{PROJECT_NAME}}-enUS.config"
# The systemd service name for project that generates and translates most of the code. 
PROJECT_SERVICE: "watch-{{PROJECT_NAME}}"
# The systemd service file for project that generates and translates most of the code. 
PROJECT_SYSTEMD: "/usr/lib/systemd/system/{{PROJECT_SERVICE}}.service"
# The main git repository for the project project. 
PROJECT_REPO: "git@github.com:Southern-Coalition-Team-19/project.git"
# The target ansible inventory group for the project project to setup your own hosts under this name to deploy the application to. 
target: redhat_project

######################
# Zookeeper defaults #
######################

# The default hostname for the Zookeeper cluster manager. 
ZOOKEEPER_HOST_NAME: "localhost"
# The default port that Zookeeper runs to manage the cluster. 
ZOOKEEPER_PORT: 2181

#################
# Solr defaults #
#################

# The installation directory of Solr. 
SOLR_OPT: /opt/solr
# The default hostname for the Solr search engine. 
SOLR_HOST_NAME: localhost
# The default port that Solr runs. 
SOLR_PORT: 8983

#######################
# PostgreSQL defaults #
#######################

# The default hostname for the PostreSQL database. 
POSTGRES_HOST_NAME: "localhost"
# The default username that the PostgreSQL server runs with. 
POSTGRES_BECOME_USER: "postgres"
# The default path to the PostgreSQL hba file to manage user permissions. 
POSTGRES_HBA_CONF: "/var/lib/pgsql/data/pg_hba.conf"
# The default PostgreSQL service name. 
POSTGRES_SERVICE: "postgresql"

#####################################
# project global defaults #
#####################################

# The base URL where the static files will point to.  
PROJECT_STATIC_BASE_URL: "https://example.neocities.org"
# The number of background worker executors that may run. 
PROJECT_NUMBER_EXECUTORS: 5
# The properties file where the SSL/TLS encryption is configured. 
PROJECT_SSL_PROPERTIES_FILENAME: project-keystore.properties

#################################################
# project English in the US defaults #
#################################################

# The domain name of the site. 
PROJECT_DOMAIN_NAME_ENUS: "example.com"
# The host name of the site. 
PROJECT_SITE_HOST_NAME_ENUS: "project-dev.{{PROJECT_DOMAIN_NAME_ENUS}}"
# The port of the site. 
PROJECT_SITE_PORT_ENUS: "10681"
# The base URL of the site. 
PROJECT_SITE_BASE_URL_ENUS: "https://{{PROJECT_SITE_HOST_NAME_ENUS}}:{{PROJECT_SITE_PORT_ENUS}}"
# The Solr collection of the site. 
PROJECT_SOLR_COLLECTION_ENUS: "project"
# The timezone of the site. 
PROJECT_SITE_ZONE_ENUS: "America/Denver"
# The PostgreSQL database host name of the site. 
PROJECT_DB_HOST_NAME_ENUS: "localhost"
# The PostgreSQL database user name of the site. 
PROJECT_DB_USER_ENUS: computate
# The PostgreSQL database password of the site. 
PROJECT_DB_PASSWORD_ENUS: "..."
# The PostgreSQL database name of the site. 
PROJECT_DB_NAME_ENUS: project
# The Java main class of the site. 
PROJECT_JAVA_MAIN_CLASS_ENUS: org.project.enus.vertx.AppVertx
# The backup directory of the site. 
PROJECT_BACKUP_DIR_ENUS: /usr/local/src/project-static/data/enUS
# The restore directory of the site. 
PROJECT_RESTORE_DIR_ENUS: /home/ctate/backup/project-dev/enUS

#################
# SMTP defaults #
#################

# The email SMTP host name. 
EMAIL_HOST_NAME: smtp.example.com
# The email SMTP port. 
EMAIL_PORT: 465
# The email SMTP from email address. 
EMAIL_FROM: "..."
# Whether email SMTP SSL/TLS encryption is enabled. 
EMAIL_SSL: true
# Whether email SMTP username password authentication is enabled. 
EMAIL_AUTH: true
# The email SMTP username. 
EMAIL_USER: "..."
EMAIL_PASSWORD: "..."

#######################################
# OpenID Connect auth server defaults #
#######################################

# The Auth realm. 
AUTH_REALM: EXAMPLE.COM
# The Auth client or resource. 
AUTH_RESOURCE: example.com
# The Auth secret. 
AUTH_SECRET: "..."
# The Auth URL. 
AUTH_URL: https://sso.example.com/auth

####################
# SSL/TLS defaults #
####################

# The keystore alias. 
SSL_ALIAS: "{{PROJECT_DOMAIN_NAME_ENUS}}"
# The keystore directory. 
SSL_KEYSTORE_PATH: /opt/keystore
# The keystore properties filename. 
SSL_PROPERTIES_FILENAME: "{{PROJECT_SSL_PROPERTIES_FILENAME}}"
# The keystore filename. 
SSL_JKS_FILENAME: "{{SSL_ALIAS}}.jks"
# The keystore path. 
SSL_JKS_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_JKS_FILENAME}}"
# The certificate filename. 
SSL_CRT_FILENAME: "{{SSL_ALIAS}}.crt"
# The certificate path. 
SSL_CRT_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_CRT_FILENAME}}"
# The private key filename. 
SSL_KEY_FILENAME: "{{SSL_ALIAS}}.key"
# The private key path. 
SSL_KEY_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_KEY_FILENAME}}"
# The p12 file password. 
SSL_P12_PASSWORD: "..."
# The keystore file password. 
SSL_JKS_PASSWORD: "{{SSL_P12_PASSWORD}}"
# The keystore file base64 encoded (base64 -w 0 /opt/keystore/heytate.com.jks). 
SSL_JKS_BASE64: "..."
# The jceks file base64 encoded (base64 -w 0 /opt/keystore/heytate.com.jceks). 
SSL_JCEKS_BASE64: "..."

####################
# Ansible defaults #
####################

# Add to an ansible-vault the username of your user on your computer (echo $HOSTNAME). 
USER_NAME: "..."
# Add to an ansible-vault the password of your user on your computer to become root for configuring the applications. 
USER_PASSWORD: "..."
# Setup the ansible user when running the playbook as your user. 
ansible_user: "{{USER_NAME}}"
# Setup the ansible sudo password as your password when running the playbook. 
ansible_sudo_pass: "{{USER_PASSWORD}}"
# Setup the ansible password for elevated privileges as your password when running the playbook. 
ansible_become_pass: "{{USER_PASSWORD}}"
# Setup the ansible password for ssh as your password when running the playbook. 
ansible_ssh_pass: "{{USER_PASSWORD}}"
# Setup the decryption password for decrypting other secrets in the playbook. 
VAULT_PASSWORD: "{{USER_PASSWORD}}"
