---
- name: Get site access token
  shell: curl -X POST -u "{{AUTH_RESOURCE}}:{{AUTH_SECRET}}" -d "grant_type=client_credentials" "{{AUTH_URL}}/realms/{{AUTH_REALM}}/protocol/openid-connect/token"
  register: AUTH_TOKEN
- name: Refresh the {{DATA_NAME_VAR}} data
  shell: "curl -X PATCH -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' -H 'Content-Type: application/json' -d '{}' '{{COMPUTATE_MEDICALE_SITE_BASE_URL_ENUS}}{{DATA_URI}}' && sleep 10"

