---
- name: Fix messed up booleans
  hosts: computate_scolaire_restore
  connection: local
  vars: 
    enrollments: "{{ lookup('file', '/home/ctate/backup/littleorchardpreschool.us/messed-up-booleans.json') | from_json }}"
  tasks: 
    - name: Get restore site access token
      shell: curl -X POST -u "{{AUTH_RESOURCE}}:{{AUTH_SECRET}}" -d "grant_type=client_credentials" "{{AUTH_URL}}/realms/{{AUTH_REALM}}/protocol/openid-connect/token"
      register: AUTH_TOKEN
    - name: loop through enrollments
      shell: "echo '{ \"setEnrollmentApproved\":{{ item.enrollmentApproved | default(\"false\") | lower }}, \"setEnrollmentImmunizations\":{{ item.enrollmentImmunizations | default(\"false\") | lower }}, \"setFamilyMarried\":{{ item.familyMarried | default(\"false\") | lower }}, \"setFamilyDivorced\":{{ item.familyDivorced | default(\"false\") | lower }}, \"setChildPottyTrained\":{{ item.childPottyTrained | default(\"false\") | lower }}, \"setEnrollmentPaymentEachMonth\":{{ item.enrollmentPaymentEachMonth | default(\"false\") | lower }}, \"setEnrollmentPaymentComplete\":{{ item.enrollmentPaymentComplete | default(\"false\") | lower }} }' | curl -X PATCH -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' -H 'Content-Type: application/json' -d @- '{{COMPUTATE_SCOLAIRE_SITE_BASE_URL_ENUS}}/api/admin/enrollment?fq=pk:{{ item.inheritPk }}' && sleep 2"
      loop: "{{ enrollments.list }}"
      loop_control: 
        label: ""

