---
- name: Restore the computate-scolaire page-design data in {{COMPUTATE_SCOLAIRE_RESTORE_DIR_ENUS}}
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: computate_scolaire_restore_enUS, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }
- name: Restore the computate-scolaire html-part data in {{COMPUTATE_SCOLAIRE_RESTORE_DIR_ENUS}}
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: computate_scolaire_restore_enUS, DATA_NAME_VAR: html-part, DATA_URI: /api/html-part }
- name: Restore the computate-scolaire page-design data again to resolve parent links in {{COMPUTATE_SCOLAIRE_RESTORE_DIR_ENUS}}
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: computate_scolaire_restore_enUS, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }

