---
- name: Deploy Crunchy PostgreSQL Operator 
  gather_facts: true
  vars:
    target: localhost
    max_storage_configs: 50  # the max num of storage configs that can be defined in the inventory
    max_resource_configs: 50  # the max num of resource configs that can be defined in the inventory
  hosts: all
  pre_tasks: 
    - name: Create pgo project
      oc: 
        state: present
        inline: 
          kind: ProjectRequest
          metadata: 
            name: pgo
          displayName: Postgres Operator
          description: Crunchy Postgres Operator
  roles: 
    - pgo-preflight 
    - pgo-operator
    - pgo-metrics


