---
- name: Install the opendatapolicing pod on OpenShift and all dependencies
  gather_facts: no
  hosts: localhost
  connection: local
  roles: 
    - redhat_sso_openshift
    - postgres_openshift
    - computate_zookeeper_openshift
    - computate_solr_openshift
    - opendatapolicing_openshift

