---
- name: Refresh the opendatapolicing page-design data
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: opendatapolicing_refresh, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }
- name: Refresh the opendatapolicing html-part data
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: opendatapolicing_refresh, DATA_NAME_VAR: html-part, DATA_URI: /api/html-part }
