---
- name: Restore the southerncoalition page-design data in {{COMPUTATE_MEDICALE_RESTORE_DIR}}
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_restore, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }
- name: Restore the southerncoalition html-part data in {{COMPUTATE_MEDICALE_RESTORE_DIR}}
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_restore, DATA_NAME_VAR: html-part, DATA_URI: /api/html-part }
- name: Restore the southerncoalition page-design data again to resolve parent links in {{COMPUTATE_MEDICALE_RESTORE_DIR}}
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_restore, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }

- name: Restore the southerncoalition state data again to resolve parent links in {{COMPUTATE_MEDICALE_RESTORE_DIR}}
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_restore, DATA_NAME_VAR: state, DATA_URI: /api/state }
- name: Restore the southerncoalition agency data again to resolve parent links in {{COMPUTATE_MEDICALE_RESTORE_DIR}}
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_restore, DATA_NAME_VAR: agency, DATA_URI: /api/agency }
- name: Restore the southerncoalition reportcard data again to resolve parent links in {{COMPUTATE_MEDICALE_RESTORE_DIR}}
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_restore, DATA_NAME_VAR: reportcard, DATA_URI: /api/reportcard }

