- name: Install {{CMAKE_NAME}} development dependencies
  package:
    name: ["@Development tools"]
  become: yes
- name: Create the {{CMAKE_NAME}} source directory {{CMAKE_SRC}}
  file:
    name: "{{CMAKE_SRC}}"
    state: directory
    owner: "{{USER_NAME}}"
  become: yes
- name: Clone the {{CMAKE_NAME}} source code
  git:
    repo: "{{CMAKE_REPO}}"
    dest: "{{CMAKE_SRC}}"
    version: "{{CMAKE_TAG}}"
- name: Boostrap the {{CMAKE_NAME}} application
  shell: ./bootstrap
  args:
    chdir: "{{CMAKE_SRC}}"
    creates: "{{CMAKE_SRC}}/bootstrap"
- name: Compiles the {{CMAKE_NAME}} application
  shell: make
  args:
    chdir: "{{CMAKE_SRC}}"
    creates: "{{CMAKE_SRC}}/bin/cmake"
- name: Installs the {{CMAKE_NAME}} application
  shell: make install
  become: yes
  args:
    chdir: "{{CMAKE_SRC}}"
    creates: "/usr/local/bin/cmake"
  register: cmakeinstall
- name: Update ldconfig
  shell: ldconfig
  become: yes
  when: cmakeinstall.changed

