---
# Title: create the Ansible playbook for deploying the complete application locally
# Mission: create the Ansible playbook for deploying the complete application locally
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

- name: Install the {{ PROJECT.PROJECT_NAME }} source code and watch service on the target. 
  hosts: localhost
  vars: 
    GITHUB_ORG: "{{ PROJECT.GITHUB_ORG }}"
    PROJECT_NAME: "{{ PROJECT.PROJECT_NAME }}"
    PROJECT_REPO: "git@github.com:\{\{ GITHUB_ORG \}\}/\{\{ PROJECT_NAME \}\}.git"
    PROJECT_SRC: "\{\{ playbook_dir \}\}"
    PROJECT_CONFIG:
      sqlTables: {{ PROJECT.PROJECT_CONFIG.sqlTables | default(true) | lower }}
      enableUserKey: {{ PROJECT.PROJECT_CONFIG.enableUserKey | default(true) | lower }}
      enableSessionId: {{ PROJECT.PROJECT_CONFIG.enableSessionId | default(true) | lower }}
      enableDeleted: {{ PROJECT.PROJECT_CONFIG.enableDeleted | default(true) | lower }}
      enableArchived: {{ PROJECT.PROJECT_CONFIG.enableArchived | default(true) | lower }}
  tasks: 
    - include_role:
        name: computate.computate_postgres
    - include_role:
        name: computate.computate_zookeeper
    - include_role:
        name: computate.computate_solr
    - include_role:
        name: computate.computate_project
      vars: 
        PROJECT_JAVA_PACKAGE: {{ PROJECT.PROJECT_POM.groupId }}.enus
        PROJECT_SERVICES: 
          - PROJECT_NAME: "\{\{ PROJECT_NAME \}\}"
            PROJECT_SRC: "\{\{ playbook_dir \}\}"
            PROJECT_JAVA_PACKAGE: {{ PROJECT.PROJECT_POM.groupId }}.enus

